'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SOUND_PATH={correct:'./assets/sounds/correct.wav',wrong:'./assets/sounds/wrong.wav',tick:'./assets/sounds/tick.wav',start:'./assets/sounds/start.wav',win:'./assets/sounds/win.wav',engine:'./assets/sounds/engine.wav'};
const audioCache={};
const state={questions:[],current:null,currentIndex:-1,used:[],subject:'math',game:'tug',theme:'math-neon',starter:'A',responder:'A',attempted:{A:false,B:false},scores:{A:0,B:0},winScore:5,countdown:15,timer:null,muted:false,names:{A:'ĐỘI XANH',B:'ĐỘI ĐỎ'},winner:null};

function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),3500)}
function typeset(){setTimeout(()=>window.MathJax?.typesetPromise?.().catch(()=>{}),0)}
function playSound(name,volume=.8){if(state.muted)return;try{let a=audioCache[name];if(!a){a=new Audio(SOUND_PATH[name]);audioCache[name]=a}a.pause();a.currentTime=0;a.volume=volume;a.play().catch(()=>{})}catch{}}
function formatMeta(q){return[q.subject,q.grade&&`Khối ${q.grade}`,q.topic].filter(Boolean).join(' • ')}
function normalizeQuestion(q,i=0){q=q||{};let opts=q.options??q.Options??[];if(!Array.isArray(opts)&&opts&&typeof opts==='object')opts=Object.keys(opts).sort().map(k=>opts[k]);if(!Array.isArray(opts))opts=[];let correct=q.correct;if(!Number.isInteger(correct)){const a=String(q.correctAnswer??q.CorrectAnswer??q.answer??'').trim().toUpperCase();if(/^[A-D]$/.test(a))correct=a.charCodeAt(0)-65;else{const n=Number(a);correct=Number.isInteger(n)?(n>=1?n-1:n):0}}return{id:q.id??q.Id??`Q${i+1}`,subject:String(q.subject??q.Subject??''),grade:String(q.grade??q.Grade??''),topic:String(q.topic??q.Topic??''),question:String(q.question??q.Question??''),image:String(q.image??q.Image??''),options:opts.map(String),correct:Math.max(0,Math.min(opts.length-1,Number(correct)||0)),explain:String(q.explain??q.Explain??q.explanation??'')}}

async function loadBank(url,label){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();state.questions=(Array.isArray(data)?data:[]).map(normalizeQuestion).filter(q=>q.question&&q.options.length>=2);state.used=[];state.current=null;$('#bankInfo').textContent=`${state.questions.length} câu • ${label}`;toast(`Đã nạp ${state.questions.length} câu ${label}.`);clearQuestion()}catch(err){toast('Không nạp được ngân hàng: '+err.message)}}
function loadSubjectBank(){state.subject=$('#subjectSelect').value;if(state.subject==='math'){if(!['math-neon','math-board'].includes($('#themeSelect').value))$('#themeSelect').value='math-neon';loadBank('./questions-math.json','Toán')}else{if(!['it-cyber','it-terminal'].includes($('#themeSelect').value))$('#themeSelect').value='it-cyber';loadBank('./questions-it.json','Tin học')}applyTheme()}
function applyTheme(){state.theme=$('#themeSelect').value;document.body.dataset.theme=state.theme;$('#themeBadge').textContent=$('#themeSelect').selectedOptions[0]?.textContent||state.theme}
function setGame(type){state.game=type;$('#gameSelect').value=type;$('#gameTitle').textContent=type==='tug'?'🪢 KÉO CO KIẾN THỨC':'🏎️ ĐUA XE KIẾN THỨC';$('#gameDesc').textContent=type==='tug'?'Trả lời đúng để kéo cờ về phía đội mình.':'Trả lời đúng để xe tăng tốc tiến về vạch đích.';mountScene();updateVisual()}
function mountScene(){const scene=$('#scene');scene.innerHTML='';if(state.game==='tug')window.TugGameVisual.mount(scene);else window.RaceGameVisual.mount(scene)}
function updateVisual(){const scene=$('#scene');if(state.game==='tug')window.TugGameVisual.update(scene,state.scores.A,state.scores.B,state.winScore);else window.RaceGameVisual.update(scene,state.scores.A,state.scores.B,state.winScore)}
function pulseVisual(team){const scene=$('#scene');if(state.game==='tug')window.TugGameVisual.pulse(scene,team);else window.RaceGameVisual.pulse(scene,team)}

function clearQuestion(){clearInterval(state.timer);state.current=null;$('#qCounter').textContent='Câu 0';$('#qMeta').textContent='Chưa có câu hỏi';$('#questionText').textContent='Bấm “CÂU TIẾP THEO” để bắt đầu.';$('#questionMedia').innerHTML='<div class="placeholder"><div class="ico">🧠</div><div>Ảnh minh họa hoặc bảng số liệu sẽ hiện ở đây</div></div>';$('#questionNote').textContent='Toán và Tin học hỗ trợ công thức MathJax, hình ảnh và câu hỏi nhiều lựa chọn.';$('#answersA').innerHTML='';$('#answersB').innerHTML='';$('#explain').innerHTML='Bấm <b>CÂU TIẾP THEO</b> để bắt đầu trận đấu.';$('#timer').textContent=$('#countdownSelect').value||'15';updateResponderUI()}
function setNames(){state.names.A=$('#teamAName').value.trim()||'ĐỘI XANH';state.names.B=$('#teamBName').value.trim()||'ĐỘI ĐỎ';$('#hudAName').textContent=state.names.A;$('#hudBName').textContent=state.names.B;$('#panelAName').textContent=state.names.A;$('#panelBName').textContent=state.names.B;updateResponderUI()}
function updateScores(){state.winScore=Math.max(1,Math.min(20,Number($('#winScoreInput').value||5)));$('#hudAScore').textContent=state.scores.A;$('#hudBScore').textContent=state.scores.B;updateVisual()}
function updateResponderUI(){const starter=state.names[state.starter],responder=state.names[state.responder];$('#starterBadge').textContent=`Mở lượt: ${starter}`;$('#responderBadge').textContent=`Đội trả lời: ${responder}`;$('#sceneStarter').textContent=`Mở lượt: ${starter}`;$('#sceneResponder').textContent=`Đội trả lời: ${responder}`;$('#stateA').textContent=state.winner?'Kết thúc':state.responder==='A'?'Đang trả lời':state.attempted.A?'Đã trả lời':'Chờ lượt';$('#stateB').textContent=state.winner?'Kết thúc':state.responder==='B'?'Đang trả lời':state.attempted.B?'Đã trả lời':'Chờ lượt';$('#panelA').classList.toggle('active',state.responder==='A'&&!state.winner);$('#panelB').classList.toggle('active',state.responder==='B'&&!state.winner);$('#panelA').classList.toggle('inactive',state.responder!=='A'&&!state.winner);$('#panelB').classList.toggle('inactive',state.responder!=='B'&&!state.winner)}
function mediaHtml(q){if(!q.image)return'<div class="placeholder"><div class="ico">🧮</div><div>Không có hình minh họa cho câu này</div></div>';return`<img src="${esc(q.image)}" alt="Hình câu hỏi" onerror="this.outerHTML='<div class=\'placeholder\'><div class=\'ico\'>🧠</div><div>Không tải được hình minh họa</div></div>'">`}
function renderQuestion(){const q=state.current;if(!q)return;$('#qCounter').textContent=`Câu ${state.used.length}/${state.questions.length}`;$('#qMeta').textContent=formatMeta(q)||'Toán / Tin';$('#questionText').textContent=q.question;$('#questionMedia').innerHTML=mediaHtml(q);$('#questionNote').innerHTML=`Đội mở lượt: <b>${esc(state.names[state.starter])}</b>. Nếu trả lời sai, quyền trả lời chuyển sang đội còn lại.`;renderAnswers();updateResponderUI();typeset()}
function renderAnswers(){const q=state.current;if(!q)return;['A','B'].forEach(team=>{const active=state.responder===team&&!state.winner;const box=$('#answers'+team);box.innerHTML=q.options.map((text,i)=>`<button class="answer" data-team="${team}" data-i="${i}" ${active?'':'disabled'}><span class="key">${String.fromCharCode(65+i)}</span><span class="txt">${esc(text)}</span></button>`).join('');$$(`#answers${team} .answer`).forEach(b=>b.onclick=()=>answerQuestion(team,Number(b.dataset.i))) });typeset()}
function startTimer(){clearInterval(state.timer);state.countdown=Number($('#countdownSelect').value||15);$('#timer').textContent=state.countdown;state.timer=setInterval(()=>{state.countdown--;$('#timer').textContent=state.countdown;if(state.countdown>0&&state.countdown<=5)playSound('tick',.5);if(state.countdown<=0){clearInterval(state.timer);timeoutTurn()}},1000)}
function timeoutTurn(){if(!state.current||state.winner)return;const team=state.responder;state.attempted[team]=true;const other=team==='A'?'B':'A';playSound('wrong');if(!state.attempted[other]){state.responder=other;$('#explain').innerHTML=`⏱️ <b>${esc(state.names[team])}</b> hết thời gian. Chuyển quyền cho <b>${esc(state.names[other])}</b>.`;renderAnswers();updateResponderUI();startTimer()}else{revealCorrect();$('#explain').innerHTML=`⏱️ Cả hai đội đều hết lượt. Đáp án đúng: <b>${String.fromCharCode(65+state.current.correct)}. ${esc(state.current.options[state.current.correct])}</b>. ${esc(state.current.explain)}`;switchStarter();typeset()}}
function nextQuestion(){if(!state.questions.length)return toast('Chưa có câu hỏi. Hãy nạp ngân hàng Toán/Tin hoặc file JSON.');state.winner=null;$('#winner').classList.remove('show');state.attempted={A:false,B:false};let avail=state.questions.map((_,i)=>i).filter(i=>!state.used.includes(i));if(!avail.length){state.used=[];avail=state.questions.map((_,i)=>i)}const idx=avail[Math.floor(Math.random()*avail.length)];state.used.push(idx);state.currentIndex=idx;state.current=state.questions[idx];state.responder=state.starter;renderQuestion();$('#explain').innerHTML=`👉 <b>${esc(state.names[state.starter])}</b> mở lượt trước.`;playSound('start');startTimer()}
function mark(team,index,cls){const b=$(`#answers${team} .answer[data-i="${index}"]`);if(b)b.classList.add(cls)}
function revealCorrect(){clearInterval(state.timer);const q=state.current;if(!q)return;['A','B'].forEach(team=>$$(`#answers${team} .answer`).forEach(b=>{b.disabled=true;if(Number(b.dataset.i)===q.correct)b.classList.add('correct')}))}
function switchStarter(){state.starter=state.starter==='A'?'B':'A';updateResponderUI()}
function answerQuestion(team,index){if(!state.current||state.winner||team!==state.responder)return;clearInterval(state.timer);const q=state.current;state.attempted[team]=true;if(index===q.correct){mark(team,index,'correct');revealCorrect();state.scores[team]++;updateScores();pulseVisual(team);playSound('correct');if(state.game==='race')playSound('engine',.35);confetti(team);$('#explain').innerHTML=`✅ <b>${esc(state.names[team])}</b> trả lời đúng và được cộng 1 điểm. ${esc(q.explain)}`;if(state.scores[team]>=state.winScore){showWinner(team);return}switchStarter()}else{mark(team,index,'wrong');playSound('wrong');const other=team==='A'?'B':'A';if(!state.attempted[other]){state.responder=other;$('#explain').innerHTML=`❌ <b>${esc(state.names[team])}</b> chưa đúng. Quyền trả lời chuyển cho <b>${esc(state.names[other])}</b>.`;renderAnswers();updateResponderUI();startTimer()}else{revealCorrect();$('#explain').innerHTML=`❌ Cả hai đội đều chưa đúng. Đáp án đúng: <b>${String.fromCharCode(65+q.correct)}. ${esc(q.options[q.correct])}</b>. ${esc(q.explain)}`;switchStarter()}typeset()}
}
function manualPoint(team){state.scores[team]++;updateScores();pulseVisual(team);confetti(team,28);$('#explain').innerHTML=`➕ Giáo viên cộng thủ công 1 điểm cho <b>${esc(state.names[team])}</b>.`;if(state.scores[team]>=state.winScore)showWinner(team)}
function showWinner(team){state.winner=team;clearInterval(state.timer);playSound('win');confetti(team,100);$('#winnerText').textContent=`${state.names[team]} CHIẾN THẮNG!`;$('#winnerSub').textContent=`Tỉ số: ${state.scores.A} - ${state.scores.B}`;$('#winner').classList.add('show');updateResponderUI()}
function resetMatch(){clearInterval(state.timer);state.used=[];state.current=null;state.currentIndex=-1;state.starter='A';state.responder='A';state.attempted={A:false,B:false};state.scores={A:0,B:0};state.winner=null;$('#winner').classList.remove('show');updateScores();clearQuestion();toast('Đã đặt lại trận đấu.')}
function confetti(team,n=45){const box=$('#confetti'),main=team==='A'?'#48dcff':'#ff6682';for(let i=0;i<n;i++){const s=document.createElement('span');s.style.left=Math.random()*100+'%';s.style.top='-20px';s.style.background=i%3===0?main:i%2===0?'#ffd45f':'#fff';s.style.animationDelay=Math.random()*.4+'s';box.appendChild(s);setTimeout(()=>s.remove(),1900)}}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}
function toggleSound(){state.muted=!state.muted;$('#soundBtn').textContent=state.muted?'🔇 Bật âm':'🔊 Tắt âm'}
function loadCustomFile(file){const r=new FileReader();r.onload=()=>{try{const raw=JSON.parse(r.result);const arr=(Array.isArray(raw)?raw:raw.questions||[]).map(normalizeQuestion).filter(q=>q.question&&q.options.length>=2);if(!arr.length)throw new Error('Không tìm thấy câu hỏi hợp lệ');state.questions=arr;state.used=[];$('#bankInfo').textContent=`${arr.length} câu • file riêng`;clearQuestion();toast(`Đã nạp ${arr.length} câu từ ${file.name}.`)}catch(err){toast('JSON lỗi: '+err.message)}};r.readAsText(file,'utf-8')}

function bind(){
  $('#subjectSelect').onchange=loadSubjectBank;$('#themeSelect').onchange=applyTheme;$('#gameSelect').onchange=()=>setGame($('#gameSelect').value);$('#teamAName').oninput=setNames;$('#teamBName').oninput=setNames;$('#winScoreInput').onchange=updateScores;$('#nextBtn').onclick=nextQuestion;$('#addA').onclick=()=>manualPoint('A');$('#addB').onclick=()=>manualPoint('B');$('#resetBtn').onclick=resetMatch;$('#fullscreenBtn').onclick=toggleFullscreen;$('#soundBtn').onclick=toggleSound;$('#winnerAgain').onclick=resetMatch;$('#jsonFile').onchange=e=>{if(e.target.files?.[0])loadCustomFile(e.target.files[0]);e.target.value=''};
}
async function bootstrap(){bind();setNames();applyTheme();setGame('tug');updateScores();await loadSubjectBank()}
document.addEventListener('DOMContentLoaded',bootstrap);
